name: Deploy contract on Dev account

on:
  push:
    branches: [main]

jobs:
  deploy-dev:
    name: Deploy contract
    runs-on: ubuntu-latest
    environment: dev.abstract-dao.testnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.11.0/cargo-near-installer.sh | sh

      - name: Deploy contract to ${{ vars.NEAR_ACCOUNT_ID }}
        run: |
          cargo near deploy --no-docker --no-abi "${{ vars.NEAR_ACCOUNT_ID }}" \
            without-init-call \
            network-config "${{ vars.NEAR_NETWORK }}" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ vars.NEAR_ACCOUNT_PUBLIC_KEY }}" \
              --signer-private-key "${{ secrets.NEAR_ACCOUNT_PRIVATE_KEY }}" \
            send
